name: passkeys_ios
description: iOS implementation of the Corbado passkeys plugin. Manages the creation of passkeys on iOS devices.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: passkeys
    platforms:
      ios:
        pluginClass: PasskeysPlugin
        dartPluginClass: PasskeysIOS

dependencies:
  flutter:
    sdk: flutter
  passkeys_platform_interface: 
    path: ../passkeys_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.0.1
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
